### PR TITLE
Set the AWS IMDS API to a specific version

### LINKED ISSUE #127: Error when accessing 'Permissions' tab of installer
When I access the `Permissions` tab of the installer, I get the following error:
```
We're sorry, but something went wrong.
If you are the application owner, check the logs for more information.
```

In talking with @bear454 , he said the issue lies with the code calling the Policy Simulator. Attached are my `cli.log` and `production.log` files, with the pertinent block being:

```
I, [2022-10-05T13:54:49.272309 #525]  INFO -- : [586bca56-34a5-4799-a2b1-0c794be8d9f7] Started GET "/aws/permissions" for 72.66.29.59 at 2022-10-05 13:54:49 +0000
I, [2022-10-05T13:54:49.273375 #525]  INFO -- : [586bca56-34a5-4799-a2b1-0c794be8d9f7] Processing by AWS::PermissionsController#show as HTML
I, [2022-10-05T13:54:49.742437 #525]  INFO -- : [586bca56-34a5-4799-a2b1-0c794be8d9f7] Completed 500 Internal Server Error in 469ms (ActiveRecord: 0.2ms | Allocations: 2638)
F, [2022-10-05T13:54:49.749041 #525] FATAL -- : [586bca56-34a5-4799-a2b1-0c794be8d9f7]
[586bca56-34a5-4799-a2b1-0c794be8d9f7] NoMethodError (undefined method `full_messages' for #<NoMethodError: undefined method `split' for nil:NilClass

      arn.split('/')[-1]
         ^^^^^^>

      flash[:danger] = t('error', message: error.full_messages)
                                                ^^^^^^^^^^^^^^
Did you mean?  full_message):
[586bca56-34a5-4799-a2b1-0c794be8d9f7]
```

[cli.log](https://github.com/SUSE-Enceladus/suse-rancher-setup/files/9716393/cli.log)
[production.log](https://github.com/SUSE-Enceladus/suse-rancher-setup/files/9716394/production.log)

### PR DESCRIPTION
**Pull request by bear454**
... instead of using 'latest'. Resolves #127

```
ec2-user@ip-192-168-10-205:~> ec2metadata --api 2021-07-15 --info
{
  "Code" : "Success",
  "LastUpdated" : "2022-10-05T15:23:49Z",
  "InstanceProfileArn" : "arn:aws:iam::[REDACTED]:instance-profile/lasso-test",
  "InstanceProfileId" : "[REDACTED]"
}
ec2-user@ip-REDACTED:~> ec2metadata --api latest --info
{
  "Code" : "Success",
  "LastUpdated" : "2022-10-05T15:23:33Z",
  "AccountId" : "[REDACTED]"
}
```

### CODE REVIEW

**Comment by bear454** [comment]
https://bugzilla.suse.com/show_bug.cgi?id=1204062

File: engines/aws/app/models/aws/metadata.rb [hunk 1]
```diff
@@ -14,7 +14,7 @@ def self.load
 
     def execute(*args)
       stdout, stderr = Cheetah.run(
-        ['ec2metadata', '--api', 'latest', *args],
+        ['ec2metadata', '--api', '2021-07-15', *args],
```
Comment (rjschwei) [inline engines/aws/app/models/aws/metadata.rb:17]: I do not see how this helps
```
~> ec2metadata --api 2021-07-15 --info
{
  "Code" : "Success",
  "LastUpdated" : "2022-10-05T18:30:34Z",
  "AccountId" : "810320120389"
}
```
```
~> ec2metadata --api latest --info
{
  "Code" : "Success",
  "LastUpdated" : "2022-10-05T18:31:12Z",
  "AccountId" : "810320120389"
}
```
Until there is a fix for ec2metadata, i.e. bsc#1204066 I think the only reliable solution is to make the http request in ` def instance_profile_arn` and access the metadata server directly.

**Review by rjschwei — APPROVED** [review]
We should make a note to address this when ec2metadata is fixed

File: engines/aws/app/models/aws/metadata.rb (hunk 1 above)
Comment (jesusbv) [reply engines/aws/app/models/aws/metadata.rb:17]: isn't the aim to have the same version even though `latest` change ? so if `latest` changed to 
whatever version (!= `2021-07-15`), `suse-rancher-setup` would still use `2021-07-15`, right ?

**Review by jesusbv — APPROVED** [review]
